Feat: Billing account page
DEFRA/water-abstraction-ui pull request #1487
Opened 2020-11-17 14:13 UTC by DGajewska

WATER-2904

* Creates billing account page
* Creates BillingAccountsService
* Updates invoiceAddress macro to new structure
* Removes old, unused template

2020-11-18 12:00 UTC, Stephan-Hough commented on src/shared/view/nunjucks/macros/crm/invoice-address.njk
> +FAO contact.fullName, agentCompany.name
need add a new line here

2020-11-18 12:10 UTC, Stephan-Hough requested changes
Depending on the further discussion in tech refinement tomorrow there might be some more refactoring required or not.

2020-11-19 12:54 UTC, DGajewska commented on src/shared/view/nunjucks/macros/crm/invoice-address.njk
> +FAO contact.fullName, agentCompany.name
Haha whoops, thank you!

2020-11-25 09:50 UTC, Stephan-Hough approved these changes

2020-11-25 09:51 UTC, merged