Reg-Pack: Resetting password as internal and external user
DEFRA/water-abstraction-ui pull request #1527
Opened 2020-12-22 08:31 UTC by DGajewska

2020-12-31 09:41 UTC, Stephan-Hough commented on test/regression/external/reset-password.spec.js
> +    expect(browser).toHaveUrlContaining('/reset_password_change_password?');
I think you need to remove the '?' as this does not appear in the URL

2021-01-04 08:37 UTC, timtamimi approved these changes

2021-01-04 12:54 UTC, timtamimi requested changes
Sorry, just spotted that this is calling the setup endpoint in `before`. This needs to come out, as WDIO is configured to globally call the setup endpoint when the testing starts. Same goes for the teardown routine.

2021-01-05 14:06 UTC, timtamimi approved these changes
I think this can be merged now. Thank you :)

2021-01-05 14:07 UTC, merged