Water-3070 Charge Version workflow tweaks
DEFRA/water-abstraction-ui pull request #1651
Opened 2021-03-26 15:30 UTC by Stephan-Hough

**Feat/water 3070 cv wf tweaks**

- Charge version workflow ID added to the session data key
- Charge version workflow ID has been added as optional query param to all the charge info and charge workflow routes. 
- User can now create as many charge version workflows from the licences page as the licence version is set to null in the charge version workflow
- The charge version work flow "To set up” tab now includes the licence version start date
- The charge version work flow “Review” tab now includes the charge version start date
- Users can now create charge versions for expired/future dated licences

2021-03-31 10:27 UTC, DGajewska requested changes

2021-03-31 13:44 UTC, Stephan-Hough commented on src/internal/views/nunjucks/charge-information/workflow-tabs/to-set-up.njk
> +                    <th class="govuk-table__header table__header--width-20" scope="col">Action</th>
Yes - I had to add this here to make sure the table looked more readable. This is something that was requested by UCD. The other tabs was signed off as it by UCD.

2021-03-31 13:45 UTC, Stephan-Hough commented on src/internal/views/nunjucks/charge-information/workflow-tabs/review.njk
> +                    <th class="govuk-table__header" scope="col">Charge <br> information <br> start date</th>
This is something that was requested by UCD.

2021-04-06 08:13 UTC, Stephan-Hough commented on src/internal/modules/charge-information/lib/routing.js
> +    if (obj[key] === undefined || ((obj[key]).length) < 1) {
we discussed and came up with an agreed solution. Thanks

2021-04-06 08:13 UTC, Stephan-Hough commented on src/internal/modules/charge-information/lib/routing.js
> +  return isEmpty(qp) ? url : `${url}?${queryString.stringify(qp)}`;
removed in the cleanObject method

2021-04-06 14:33 UTC, DGajewska approved these changes

2021-04-07 13:33 UTC, merged